#!/bin/bash -e
# Konnov, Alexander A. "Yet another kinetic mechanism for hydrogen combustion." Combustion and Flame 203 (2019): 14-22.
# https://doi.org/10.1016/j.combustflame.2019.01.032
# https://www.sciencedirect.com/science/article/pii/S0010218019300501?casa_token=gLi_hgHZj-kAAAAA:P-X_wGvinanMfhSQFitNeTFnmUwPkVzYNPwjw5ZmjEk3RvuRMqSsorWqGQwYG3Zfi3_BuBKfGg#ecom0001
# Mechanism contains 15 species and 75 reactions.

MECH=${PWD##*/}

cd ..
source ./setpaths $MECH
mkdir $DIR_CHEMKIN

echo "Getting files from web"
mkdir TEMP
wget --output-document=TEMP/$MECH.zip https://ars.els-cdn.com/content/image/1-s2.0-S0010218019300501-mmc2.zip
unzip TEMP/$MECH.zip -d TEMP

mv TEMP/H2_new_mech/H2_new_mech.txt  $CHEMKIN_CHEM
mv TEMP/H2_new_mech/excite_therm.txt $CHEMKIN_THERMO
mv TEMP/H2_new_mech/H2_new_trans.txt $CHEMKIN_TRANSPORT
rm -r TEMP

# Reactions (1, 72), (6,74), (7,75) are duplicate

echo "Done"
