#!/bin/bash

MECH=$1

if [ ! -d "$MECH" ]; then
    echo "Please provide mechanism name"
    exit 1
fi
. ./setpaths $MECH

echo "[$0] Cleaning mechanism $MECH folder"
rm -rf $DIR_CANTERA $DIR_PYJAC
rm -f $MECH/log*
