#!/bin/bash -e
# Stagni, Alessandro, et al. "Low-and intermediate-temperature ammonia/hydrogen oxidation in a flow reactor: Experiments and a wide-range kinetic modeling." Chemical Engineering Journal 471 (2023): 144577.
# https://doi.org/10.1016/j.cej.2023.144577
# https://ars.els-cdn.com/content/image/1-s2.0-S1385894723033089-mmc2.zip
# Mechanism contains 31 species and 203 reactions.

MECH=${PWD##*/}

cd ..
source ./setpaths $MECH
mkdir $DIR_CHEMKIN

echo "Getting files from web"
mkdir TEMP
wget --output-document=TEMP/$MECH.zip https://ars.els-cdn.com/content/image/1-s2.0-S1385894723033089-mmc2.zip
unzip TEMP/$MECH.zip -d TEMP

mv TEMP/chem.dat  $CHEMKIN_CHEM
mv TEMP/therm.dat $CHEMKIN_THERMO
mv TEMP/tran.dat  $CHEMKIN_TRANSPORT
rm -r TEMP
echo "Done"
