#!/bin/bash -e
# Stagni, Alessandro, et al. "An experimental, theoretical and kinetic-modeling study of the gas-phase oxidation of ammonia." Reaction Chemistry & Engineering 5.4 (2020): 696-711.
# https://doi.org/10.1039/C9RE00429G
# https://www.rsc.org/suppdata/c9/re/c9re00429g/c9re00429g1.zip

MECH=${PWD##*/}

cd ..
source ./setpaths $MECH
mkdir $DIR_CHEMKIN


echo "Getting files from web"
mkdir TEMP
wget --output-document=TEMP/$MECH.zip https://www.rsc.org/suppdata/c9/re/c9re00429g/c9re00429g1.zip
unzip TEMP/$MECH.zip -d TEMP

mv TEMP/chem.dat  $CHEMKIN_CHEM
mv TEMP/therm.dat $CHEMKIN_THERMO
mv TEMP/tran.dat  $CHEMKIN_TRANSPORT
rm -r TEMP
echo "Done"
