#!/bin/bash -e
# https://github.com/OpenFOAM/OpenFOAM-9/tree/master/tutorials/combustion/reactingFoam/RAS/SandiaD_LTS/chemkin
# Mechanism contains 36 species and 219 reactions.

MECH=${PWD##*/}

cd ..
source ./setpaths $MECH
mkdir $DIR_CHEMKIN

PATH_SANDIAD=/opt/openfoam9/tutorials/combustion/reactingFoam/RAS/SandiaD_LTS
WEB_GRI_TRANSPORT=http://combustion.berkeley.edu/gri-mech/version30/files30/transport.dat

echo "Copying files from openfoam SandiaD tutorial"
# chemkin folder:
cp $PATH_SANDIAD/chemkin/grimech30.dat $CHEMKIN_CHEM
cp $PATH_SANDIAD/chemkin/thermo30.dat $CHEMKIN_THERMO
# cp $PATH_SANDIAD/chemkin/transportProperties $CHEMKINTOFOAM_TRANSPORT
# openfoam folder:
# cp $PATH_SANDIAD/constant/reactionsGRI $OPENFOAM_CHEM
# cp $PATH_SANDIAD/constant/thermo.compressibleGasGRI $OPENFOAM_THERMO
echo "Done"

echo "Getting files from web"
wget --output-document=$CHEMKIN_TRANSPORT $WEB_GRI_TRANSPORT
echo "Done"
