#!/bin/bash -e
# Gregory P. Smith, David M. Golden, Michael Frenklach, Nigel W. Moriarty, Boris Eiteneer, Mikhail Goldenberg, C. Thomas Bowman, Ronald K. Hanson, Soonho Song, William C. Gardiner, Jr., Vitali V. Lissianski, and Zhiwei Qin http://www.me.berkeley.edu/gri_mech/
# http://combustion.berkeley.edu/gri-mech/version30/text30.html
# Mechanism contains 53 species and 325 reactions.

MECH=${PWD##*/}

cd ..
source ./setpaths $MECH
mkdir $DIR_CHEMKIN

WEB_CHEM=http://combustion.berkeley.edu/gri-mech/version30/files30/grimech30.dat
WEB_THERMO=http://combustion.berkeley.edu/gri-mech/version30/files30/thermo30.dat
WEB_TRANSPORT=http://combustion.berkeley.edu/gri-mech/version30/files30/transport.dat
PATH_CHEMKINTOFOAM_TRANSPORT=/opt/openfoam8/tutorials/combustion/reactingFoam/RAS/SandiaD_LTS/chemkin/transportProperties

echo "Getting files from web"
wget --output-document=$CHEMKIN_CHEM $WEB_CHEM
wget --output-document=$CHEMKIN_THERMO $WEB_THERMO
wget --output-document=$CHEMKIN_TRANSPORT $WEB_TRANSPORT
echo "Done"

echo "Warning! Changing THERMO to THRMO ALL for chemkinToFoam"
sed -i 's/THERMO/THERMO ALL/' $CHEMKIN_THERMO
